stages:
  - build
  - deploy

build:
  stage: build
  only:
    refs:
      - main
  script:
    - docker build --no-cache -t chat-server:latest server
    - docker build --no-cache -t chat-client:latest client

deploy:
  stage: deploy
  only:
    refs:
      - main
  script:
    - docker-compose -f server/docker-compose.yml up -d
    - docker-compose -f client/docker-compose.yml up -d
